### ISSUE TITLE
Use  setLoading operator

### ISSUE THREAD

**Issue by NetanelBasal** [trungk18/jira-clone-angular#49]
You've missed this operator :)

https://datorama.github.io/akita/docs/additional/operators#setloading

**Comment by trungk18** [comment]
@NetanelBasal Thanks, I will update the code tomorrow. I think I saw that operator but didn't really take a closer look on that.

**Comment by trungk18** [comment]
@NetanelBasal Fixed in https://github.com/trungk18/jira-clone-angular/pull/51. Thanks for your suggestion
