### ISSUE TITLE
When adding the new ticket, the assignees dropdown was not render correctly after searching

### ISSUE THREAD

**Issue by trungk18** [trungk18/jira-clone-angular#52]
**Describe the bug**
When adding the new ticket, the assignees dropdown was not render correctly after search for a certain user.

**To Reproduce**
1. Open Add new issue modal
2. Search for an user on the assignee.
3. Clear the text.

**Expected behavior**
The user should be render all the time./

**Screenshots**

It is listed here https://jira.trungk18.com/project/issue/9667

![Assignee bug](https://raw.githubusercontent.com/trungk18/jira-clone-angular/master/frontend/src/assets/img/assignee-bug.gif)

**Desktop (please complete the following information):**
Chrome

**Comment by harshilparmar** [comment]
Can I try this?

**Comment by trungk18** [comment]
Sure, create a PR once you fix it please!

**Comment by patelvimal** [comment]
@trungk18 This seems to be bug in nz-select when nz-optionn using with "nzCustomContent" . Once I updated the "ng-zorro-antd" version from 9.1.2 to latest version, this issues is resolved.

**Comment by trungk18** [comment]
@patelvimal Thanks for letting me know. I already upgraded ng-zorro to v10 last few weeks.
Just do a quick test on [jira.trungk18.com](https://jira.trungk18.com/project/board), it has been fixed
