### ISSUE TITLE
Graphql Dev kits

### ISSUE THREAD

**Issue by jason8448** [trungk18/jira-clone-angular#60]
https://www.apollographql.com/docs/
https://hasura.io/

**Comment by trungk18** [comment]
@jason8448 Thanks for your suggestion. We are using @nestjs/graphql package. It is still working in progress but you can take a look at the code

https://github.com/trungk18/jira-clone-angular/blob/feature/login/ngvn/apps/api/src/app/gql.module.ts

And this is how it looks.

https://twitter.com/tuantrungvo/status/1279719344985927680
