### ISSUE TITLE
Business analysis

### ISSUE THREAD

**Issue by Jane-Tran** [trungk18/jira-clone-angular#62]
Không biết có thêm phần phân  tích thiết kế back-end ko ạ ?, nếu có thì cho em xin thêm thông để có thể triển khai thiết kết Database và viết API 
Chân thành cảm ơn tác giả, e đã start cho tác giả rồi nhé

**Comment by trungk18** [comment]
Cảm ơn @Jane-Tran nhé. Hiện tại bọn anh đang code backend. Documentation chắc còn lâu nữa mới viết được do cả hai đều đang bận một số việc dang dở. Em có thể tham khảo phần code backend ở branch này. 

https://github.com/trungk18/jira-clone-angular/tree/feature/gql/ngvn

Trong đó cũng có đủ schema database. Phần authentication backend cũng coi như là xong rồi.
