### ISSUE TITLE
[Project style] Use Nrwl nx tooling to help manage the project in a mono-repo

### ISSUE THREAD

**Issue by ubergeoff** [trungk18/jira-clone-angular#73]
**Is your feature request related to a problem? Please describe.**
It's a bit difficult when building a front and back end project in the same workspace:
Managing things like deployments and common dependencies can become tricky.
Slitting code up into re-usable libraries - that are isolated from the main application

**Describe the solution you'd like**
I would like to request that you/we make use of the nrwl nx extensions within this project - thus helping to manage a mono-repo styles project like this easier.

**Additional context**
Nx is an open platform with plugins for many modern tools and frameworks. It has support for TypeScript, Angular, Cypress, Jest, Prettier and Nest.js, among others. With Nx, you get a consistent dev experience regardless of the tools used.

https://nx.dev/angular/getting-started/why-nx

Naturally I would be happy to help - if needs be..?

**Comment by trungk18** [comment]
Thanks for your suggestion @ubergeoff !

I am actually working with the Nx Workspace for the proper API with NestJS and GraphQL. You can see the current code on that branch

https://github.com/trungk18/jira-clone-angular/tree/feature/gql

Hope it clarifies.
